# Generated by Django 4.2.7 on 2023-12-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_reservation_room_delete_client_reservation_room_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
